name: CI tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libgtk-4-dev
      - name: Install roswell
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install qlot
        run: |
          ros install qlot
      - name: Set Path
        run: |
          echo "${HOME}/.roswell/bin" >> $GITHUB_PATH
      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          qlot install
          qlot exec ros -l ci/build.lisp
      - name: Generate release message
        run: echo "Version ${{ github.ref_name }}" > release-msg.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        body_path: release-msg.txt
        with:
          files: src/voxview
