name: Build release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libgtk-4-dev
      - name: Install roswell
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install qlot
        run: |
          ros install qlot
      - name: Set Path
        run: |
          echo "${HOME}/.roswell/bin" >> $GITHUB_PATH
      - name: Build a standalone executable
        run: |
          cd $GITHUB_WORKSPACE
          qlot install
          qlot exec ros dynamic-space-size=16gb -l ci/build.lisp
          mv src/voxview .
          tar cvf voxview-ubuntu-x86-64-${{ github.ref_name }}.tar voxview
          gzip voxview-ubuntu-x86-64-${{ github.ref_name }}.tar
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: voxview-ubuntu-x86-64-${{ github.ref_name }}.tar.gz
